{"name": "testsquare", "status": "failed", "statusDetails": {"message": "AssertionError: assert 49 == 40\n  -49\n  +40", "trace": "@pytest.mark.square\n    def testsquare():\n        num = 7\n>       assert 7 * 7 == 40\nE       assert 49 == 40\nE         -49\nE         +40\n\ntest_square.py:15: AssertionError"}, "start": 1573041325545, "stop": 1573041325545, "uuid": "f797ff9e-8943-4516-9712-6ff60e36b811", "historyId": "b6ba43bb87d8f36209edc28f53c017c0", "testCaseId": "8aa5f70384fcf07210637296cb238a62", "fullName": "test_square#testsquare", "labels": [{"name": "tag", "value": "square"}, {"name": "suite", "value": "test_square"}, {"name": "host", "value": "SIVA-PC"}, {"name": "thread", "value": "8312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_square"}]}